#!/usr/bin/env python
import duckduckgo
import sys
import getopt


def usage():
    sys.stderr.write("Usage: ddg [options] <keywords>")
    sys.stderr.write("    -n N    return N search results")


def main():
    max_results = 0

    try:
        optlist, args = getopt.getopt(sys.argv[1:], "n:")
    except getopt.GetoptError as err:
        sys.stderr.write(err)
        sys.exit(2)

    for o, a in optlist:
        if o == "-n":
            max_results = int(a)

    if len(args) < 1:
        usage()
        sys.exit(2)

    keywords = args

    for result in duckduckgo.search(keywords, max_results=max_results):
        print(result)


if __name__ == "__main__":
    main()

